name: Demo GitHub Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    steps:
      - name: 22f1000539@ds.study.iitm.ac.in
        run: echo "Hello, world!"
